language: node_js
node_js:
#   - "0.6"     # no longer supported by async
#   - "0.8"     # no longer supported by iconv
#   - "0.10"    # no longer maintained by node.js
    - "4"
#   - "5"       # no longer maintained by node.js (see node 7)
    - "6"

services:
    - redis-server
    
# these are required for building on node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - "CXX=g++-4.8"
# end: these are required for building on node.js v4

before_script:
    - npm install -g grunt-cli

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run coverage
    - ./node_modules/.bin/codecov

sudo: false
