on: [ pull_request ]

name: Test Coverage

env:
  node_version: 14

jobs:

  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      name: Checkout Haraka
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}

    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y libarchive-tools
        npm install
        npm install --no-save nyc codecov

    - run: npm run cover

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
