name: Lint

on: [ push, pull_request ]

env:
  CI: true
  node_version: 14

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14 ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout Haraka
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v3
      name: Use Node.js ${{ env.node_version }}
      with:
        node-version: ${{ env.node_version }}

    - run: npm install

    - run: npm run lint

